name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/zzdb/opensearch-mcp:v0.1.0
        docker push registry.cn-hangzhou.aliyuncs.com/zzdb/opensearch-mcp:v0.1.0 
